# Generated by Django 4.2 on 2023-04-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_tablereversed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereversed',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
